[book]
title = "IFTAS RFCs"
description = "Proposals for improving the moderation and trust & safety for the Fediverse"
language = "en"
multilingual = false

[build]
build-dir = "build"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/iftas-org/rfcs"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.search]
heading-split-level = 0

[output.html.playground]
runnable = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
