[book]
title = "The IFTAS RFC Book"

[build]
build-dir = "build"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/iftas-org/rfcs"

[output.html.search]
heading-split-level = 0

[output.html.playground]
runnable = false
