name: Automatic Rebase

# NOTE: If we have additional actions to run, such as with any sort of linting / CI,
# we'll need to use the Personal Access Token approach for handling the rebases:
#
#     - name: Checkout the latest code
#       uses: actions/checkout@v3
#       with:
#         token: ${{ secrets.PAT_TOKEN }}
#         fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
#     - name: Automatic Rebase
#       uses: cirrus-actions/rebase@1.8
#       env:
#         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '/rebase') || 
        contains(github.event.comment.body, '/autosquash')
      )
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: ${{ contains(github.event.comment.body, '/autosquash') || contains(github.event.comment.body, '/rebase-autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
